<a href="https://colab.research.google.com/github/srumangala/Tensorflow_Basics/blob/main/tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is an intro to tensorlow with the basics.
---

Importing tensorflow.

---

In [1]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


Specifying tensorflow variables of tensors below.

---

In [3]:
tensor_string = tf.Variable('String1', tf.string)
tensor_int = tf.Variable(321, tf.int16)

Rank = no. of dimensions involved. numpy = 2,3, etc. (this is the rank)

---



In [18]:
tensor_r1 = tf.Variable([[1,2],[3,4],[5,6]],tf.int16)
tensor_r2 = tf.Variable([[[12.1,13.2],[13.4,0],[14.6,2]],[[2,3],[4,5],[5.325,66]]],tf.float64)
print(tensor_r2)
tf.rank(tensor_r1)


<tf.Variable 'Variable:0' shape=(2, 3, 2) dtype=float32, numpy=
array([[[12.1  , 13.2  ],
        [13.4  ,  0.   ],
        [14.6  ,  2.   ]],

       [[ 2.   ,  3.   ],
        [ 4.   ,  5.   ],
        [ 5.325, 66.   ]]], dtype=float32)>


<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [12]:
tf.rank(tensor_r2)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

Shape of tensor.

---

In [13]:
tensor_r1.shape

TensorShape([3, 2])

In [15]:
tensor_r2.shape

TensorShape([2, 3, 2])

Changing Shape of tensor
---

In [20]:
tensor1 = tf.ones([1,2,3])
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [30]:
tensor2 = tf.ones([4,3,2])
#print(tensor2)

In [31]:
tensor3 = tf.reshape(tensor1,[2,3,1] )
#print(tensor3)

In [32]:
tensor4 = tf.reshape(tensor2, [2,3,4])
#print(tensor4)

Check below. [4,-1] implies it will change original tensor of [4,3,2] into [4, 3*2] = [4,6]

In [29]:
tensor5 = tf.reshape(tensor2, [4,-1])
print(tensor5)

tf.Tensor(
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]], shape=(4, 6), dtype=float32)
